### ISSUE TITLE
Switch `cpplib.py::collect_files` to `git ls-tree`?

### ISSUE THREAD

**Issue by matz-e** [BlueBrain/hpc-coding-conventions#104]
Compile commands require basic dependencies to be present and a full CMake execution. For a quick formatting test, this seems a bit of overkill (especially if this should be run very early in the CI).

Switching from relying on compile commands to grabbing the included repository files via `git ls-tree` may be simpler, quicker, and also include files that may not be compiled by default. It would be nice if we could have a standalone-executable that will merge the YAML configurations, get files from `git ls-tree` and filters out C++ files and headers and runs the formatting check with a minimum amount of dependencies.

**Comment by olupton** [comment]
(See also: internal ticket [HPCTM-1416](https://bbpteam.epfl.ch/project/issues/browse/HPCTM-1416).)

**Comment by ohm314** [comment]
We discussed this within the team today and the conclusion is that using `git ls-tree` is a good alternative. The advantage is that there is no need to run cmake beforehand, which would require dependencies to be built. The majority felt that we should give the new solution a try, if the PR looks nice it will replace `cpplib.py::collect-files`.

**Comment by olupton** [comment]
> and also include files that may not be compiled by default

A real world example of this is CUDA code in CoreNEURON, which is not enabled in the GA CI job that checks formatting.

**Comment by pramodk** [comment]
@alkino: when you would have some time in coming days, may be you can take a look at this issue? today we saw that this will be also useful in https://github.com/neuronsimulator/nrn/pull/1748.

**Comment by alkino** [comment]
First *draft*:
`git ls-tree --full-tree -r <GIT_BRANCH>`
