### ISSUE TITLE
Improve escaping of script arguments

### ISSUE THREAD

**Issue by olupton** [BlueBrain/hpc-coding-conventions#117]
We currently have to put a lot of backslashes in project configuration like:
https://github.com/neuronsimulator/nrn/blob/710d2ca0a9e96cddb3dce98647ed015527e298f6/CMakeLists.txt#L622-L627
because hpc-coding-conventions does not do enough escaping when generating targets such as `clang-format` and `check-clang-format`.

We should be able to write down Python regular expressions without having to worry about shell escapes as well.

See also: https://github.com/BlueBrain/hpc-coding-conventions/pull/115#discussion_r840520517

**Comment by tristan0x** [comment]
IMO this issue can be closed since such regular expressions are now specified in the `.bbp-project.yaml` at the root of a project. See the default YAML file [bbp-project.yaml](https://github.com/BlueBrain/hpc-coding-conventions/blob/8cc32b09dd4609b333c871817b96294fea0b71f2/bbp-project.yaml)

**Comment by tristan0x** [comment]
> IMO this issue can be closed since such regular expressions are now specified in the `.bbp-project.yaml` at the root of a project. See the default YAML file [bbp-project.yaml](https://github.com/BlueBrain/hpc-coding-conventions/blob/8cc32b09dd4609b333c871817b96294fea0b71f2/bbp-project.yaml)

I let you close this issue @olupton if this is fine with you
