### ISSUE TITLE
One argument per line is quite a bit to read

### ISSUE THREAD

**Issue by tristan0x** [BlueBrain/hpc-coding-conventions#18]
@matz-e just mentioned that he dislikes what cmake-format is currently doing for function calls having more than 3 parameters:

```cmake
common_find_package(Boost
                    1.54.0
                    REQUIRED
                    COMPONENTS
                    filesystem
                    thread
                    system
                    numpy${USE_BOOST_PYTHON_VERSION}
                    python${USE_BOOST_PYTHON_VERSION}
                    unit_test_framework)
```

with cmake-format parameter `max_subargs_per_line: 10`, then line above becomes:

```cmake
common_find_package(Boost 1.54.0 REQUIRED COMPONENTS filesystem thread system
                    numpy${USE_BOOST_PYTHON_VERSION} python${USE_BOOST_PYTHON_VERSION}
```

Let's discuss this matter in this issue.

**Comment by tristan0x** [comment]
### if `max_subargs_per_line` is too big, then it becomes unreadable

To me, the snippet above is a bit dense to read:
```
common_find_package(Boost 1.54.0 REQUIRED COMPONENTS filesystem thread system
                    numpy${USE_BOOST_PYTHON_VERSION} python${USE_BOOST_PYTHON_VERSION}
```
In this case I prefer to split arguments, one per line.

### But I partially agree with @matz-e

I am not against increasing a little bit `max_subargs_per_line` to `5` for instance so that it does not break for function calls that are still readable in one line.

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 37c6e0a..55ac723 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -54,10 +54,7 @@ set(FLATINDEX_DESCRIPTION "Spatial Indexer (FLATIndex) Tool for the Blue Brain P
 
 # as SpatialIndex is opensource package, no plan to fix the warnigns from that code. We will have
 # new version in the near future.
-string(REPLACE "-Werror"
-               ""
-               CMAKE_CXX_FLAGS
-               "${CMAKE_CXX_FLAGS}")
+string(REPLACE "-Werror" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
 
 add_subdirectory(spatialindex)
 add_subdirectory(FLAT)
```

**Comment by ferdonline** [comment]
I thought "not-breaking-when-fits-line" was the default. 
I'm totally for allowing multiple arguments together. 5 sounds fine

**Comment by matz-e** [comment]
I think my main issue here is that my brain needs to do more work to figure out the intent. Part of this may be the hideousness of CMake itself. Ideally, I would break this down logically like this somehow:
```
common_find_package(Boost 1.54.0
                    REQUIRED
                    COMPONENT filesystem
                              thread
                              system
                              numpy${USE_BOOST_PYTHON_VERSION}
                              python${USE_BOOST_PYTHON_VERSION}
                              unit_test_framework)
```
The "beauty" of CMake may not allow for that, in which case one arg per line should be fine.

**Comment by pramodk** [comment]
As cmake files evolves, they slowly become hard to comprehend. I am up for anything that make code clean and easy to comprehend (e.g. above @matz-e's example or anything similar).

**Comment by tristan0x** [comment]
> I think my main issue here is that my brain needs to do more work to figure out the intent. Part of this may be the hideousness of CMake itself. Ideally, I would break this down logically like this somehow:
> 
> ```
> common_find_package(Boost 1.54.0
>                     REQUIRED
>                     COMPONENT filesystem
>                               thread
>                               system
>                               numpy${USE_BOOST_PYTHON_VERSION}
>                               python${USE_BOOST_PYTHON_VERSION}
>                               unit_test_framework)
> ```
> The "beauty" of CMake may not allow for that, in which case one arg per line should be fine.

I nice this would be a nice patch in cmake-format

**Comment by tristan0x** [comment]
I have just figured that cmake_format doesn't use uppercase words to figure out keywords and arguments. It actually knows the functions attributes
https://github.com/cheshirekow/cmake_format/blob/master/cmake_format/commands.py

It is possible to provide additional functions in the `additional_commands` key. For instance:
```yaml
additional_commands:
  common_find_package:
    pargs: \*
    flags: [EXACT, MODULE, REQUIRED, NO_POLICY_SCOPE, QUIET]
    kwargs:
      COMPONENT: '*'
      OPTIONAL_COMPONENTS: '*'
# [...]
```

et voilà!

```cmake
find_package(Boost 1.54.0 REQUIRED
             COMPONENTS filesystem
                        thread
                        system
                        numpy${USE_BOOST_PYTHON_VERSION}
                        python${USE_BOOST_PYTHON_VERSION}
                        unit_test_framework)

common_find_package(Boost 1.54.0 REQUIRED
                    COMPONENT filesystem
                              thread
                              system
                              numpy${USE_BOOST_PYTHON_VERSION}
                              python${USE_BOOST_PYTHON_VERSION}
                              unit_test_framework)
```

At the moment, hpc-coding-convention submodule overwrites file `.cmake-format.yaml` in `${PROJECT_SOURCE_DIR}`, which means that all additional commands would have to be specified in hpc-coding-conventions. This is not a viable solution. Every project should have the possibility to set `additional_commands` at will.
YAML changes in hpc-coding-conventions should be merged in `${PROJECT_SOURCE_DIR}/.cmake-format.yaml` instead.

**Comment by matz-e** [comment]
I like how that reads! Thank you for unearthing that!

**Comment by tristan0x** [comment]
Since f0ca4d22e, it is possible to customize cmake-format configuration by providing a file named `.cmake-format.changes.yaml` in ${PROJECT_SOURCE_DIR}
You can specify in this file how cmake-format should format your owned functions and macros.
