### ISSUE TITLE
Inconsistency from  `BinPackArguments: True` in .clang-format

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/hpc-coding-conventions#26]
Use of bin-packing result into different structuring for `methods` and `extern_definitions `. 

![Screenshot 2019-04-14 at 14 49 59](https://user-images.githubusercontent.com/666852/56093127-e760ea00-5ec4-11e9-9cf6-8e92d71487db.png)

And there are other examples. I see ``BinPackArguments: False` as a reasonable default when I tried with NMODL project. I wonder what is impact of this on other projects.

**Comment by tristan0x** [comment]
Fixed by #27
