### ISSUE TITLE
suggestion: endorsing or allowing alternate doc comment style for C++

### ISSUE THREAD

**Issue by ohm314** [BlueBrain/hpc-coding-conventions#29]
The current recommendations state that `///` is recommended / preferred. I would like to propose the alternate style

```c++
/**
 *
 */
```

to be used or left as an option to the project creator/owner. This is probably mostly a matter of taste, but I find this style a little cleaner (whatever that means...).

**Comment by matz-e** [comment]
I concur.

**Comment by tristan0x** [comment]
Link to [current documentation](https://github.com/BlueBrain/hpc-coding-conventions/blob/master/cpp/Documentation.md#documentation-style)

**Comment by tristan0x** [comment]
Can the reviewers vote, please?

**Comment by pramodk** [comment]
I find `///` syntax handy for one liner comment but `/**  */` nicer for multi-line comment blocks. (again, just matter of taste)

**Comment by ferdonline** [comment]
According to google C++ style (https://google.github.io/styleguide/cppguide.html#Comment_Style)
one shall use either one or the other, and be consistent. I agree with that.
I personally also prefer /**  */ but we shall not change projects where /// is already used.
