### ISSUE TITLE
cmake-format should only run on cmake files that are being committed

### ISSUE THREAD

**Issue by ohm314** [BlueBrain/hpc-coding-conventions#36]
It looks like `cmake-format` is run on almost every possible cmake file in the repo, regardless of whether it is a generated cmake file in the build directory or not and whether the cmake file is being changed in the commit:

https://github.com/BlueBrain/hpc-coding-conventions/blob/20e6e6f60f9f5671d779edc715fea5b3d8540695/cpp/cmake/bbp-cmake-format.py#L45

In large projects, with multiple targets this results in many redundant and useless checks.

**Comment by matz-e** [comment]
FWIW, I think this should be a general principle of commit-hooks: only look at the files actually changed by the commit hook. Same should apply to all Python/C++ files.

**Comment by ohm314** [comment]
You're right. I'll try to push a proposal in the next 2 days

**Comment by tristan0x** [comment]
FYI, current pre-commits trigger the `check-clang-tidy` and `check-clang-format` make targets, see
https://github.com/BlueBrain/hpc-coding-conventions/blob/master/cpp/cmake/bbp-setup-pre-commit-config.py

To implement this, you must update the pre-commit config to pass the modified files, find a way to pas them to the make target (maybe through environment variable), and update the python script accordingly.

**Comment by ohm314** [comment]
thanks! I'll look into it
