### ISSUE TITLE
Clang format v8 not accepted

### ISSUE THREAD

**Issue by ferdonline** [BlueBrain/hpc-coding-conventions#46]
Clang format v8 is not accepted by coding conventions cmake

> Could NOT find ClangFormat: Found unsuitable version "8.0.0", but required
  is exact version "7" (found /usr/local/bin/clang-format

**Comment by matz-e** [comment]
That's on purpose to fix the formatting, which may change between `clang-format` versions.

**Comment by tristan0x** [comment]
If code formatting doesn't change for nmodl and basalt, I don't have anything against allowing LLVM 8.

**Comment by ferdonline** [comment]
> which may change between clang-format versions.

Right, by I wouldn't expect changes, at least not significant. Even if there are, if we do clang-format only to modified files the changes will be self contained and easy to spot, which sound ok to me

**Comment by matz-e** [comment]
> > which may change between clang-format versions.
> 
> Right, by I wouldn't expect changes, at least not significant. Even if there are, if we do clang-format only to modified files the changes will be self contained and easy to spot, which sound ok to me

We format all files that are present in `compile_commands.json`, not just the modifications.

**Comment by tristan0x** [comment]
If clang-format-8 formats differently, then a change in `.clang-format` should be enough so that it behaves like 7.

**Comment by tristan0x** [comment]
Fixed by #52
