### ISSUE TITLE
cmake-format should keep comment blocks as it is

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/hpc-coding-conventions#56]
CMake files can have formatted comment blocks and we would like to keep them as it is. For example, here is the result of cmake-format:

<img width="731" alt="image" src="https://user-images.githubusercontent.com/666852/68995514-d615fc80-085c-11ea-83cd-90258cbe47e4.png">

**Comment by pramodk** [comment]
Overlooked details, this can  be achieved via fence:

```
# ~~~
...
...
# ~~~
```

**Comment by matz-e** [comment]
> Overlooked details, this can be achieved via fence:
> 
> ```
> # ~~~
> ...
> ...
> # ~~~
> ```

Good to know, but seems not that sensible that we couldn't turn that off via an option / that it does not recognize lists in comments.
