### ISSUE TITLE
Standardize location of submodules

### ISSUE THREAD

**Issue by tristan0x** [BlueBrain/hpc-coding-conventions#68]
@matz-e recently wrote:
>  do we have a standard way to include 3rd party software as a submodule? In our open-source projects, we use extlib (libSONATA), 3rdparty (MorphIO), src/third_party (basalt), just dumping stuff into the project root and using the CMake/Common equivalent to Robert [a.k.a. bob] (Brion, Braynz), deps (Brayns)…

These conventions should provide guidelines regarding this matter.

**Comment by tristan0x** [comment]
`3rdparty` has been voted.

**Comment by tristan0x** [comment]
I am in favor of allowing a project to organize the `3rdparty` directory as will, for instance:

```
3rdparty
├── hpc-coding-conventions 🠘 will be bbp-coding-conventions soon
├── src
│   ├── catch2
│   ├── cereal
│   ├── fmt
│   ├── gsl-lite
│   ├── nlohmann
│   ├── pybind11
│   └── spdlog
└── tests
    ├── integration
    └── non-regression
```

Any objection?

**Comment by alkino** [comment]
I was thinking of maybe having a directory `BlueBlain/CMake` full of autoloaders , so maybe having the dependencies (always the same) standardized can be a good choice.

**Comment by matz-e** [comment]
> I am in favor of allowing a project to organize the `3rdparty` directory as will, for instance:
> 
> ```
> 3rdparty
> ├── hpc-coding-conventions 🠘 will be bbp-coding-conventions soon
> ├── src
> │   ├── catch2
> │   ├── cereal
> │   ├── fmt
> │   ├── gsl-lite
> │   ├── nlohmann
> │   ├── pybind11
> │   └── spdlog
> └── tests
>     ├── integration
>     └── non-regression
> ```
> 
> Any objection?

Honestly, I think for most projects this is overkill.

**Comment by tristan0x** [comment]
> > I am in favor of allowing a project to organize the `3rdparty` directory as will, for instance:
> > ```
> > 3rdparty
> > ├── hpc-coding-conventions 🠘 will be bbp-coding-conventions soon
> > ├── src
> > │   ├── catch2
> > │   ├── cereal
> > │   ├── fmt
> > │   ├── gsl-lite
> > │   ├── nlohmann
> > │   ├── pybind11
> > │   └── spdlog
> > └── tests
> >     ├── integration
> >     └── non-regression
> > ```
> > 
> > 
> > Any objection?
> 
> Honestly, I think for most projects this is overkill.

I am not sure you understood my proposal. I suggest that the only thing these conventions should recommend is the root location of all git submodules.
How it is structured inside should be left at the project's discretion.

**Comment by tristan0x** [comment]
> I was thinking of maybe having a directory `BlueBlain/CMake` full of autoloaders , so maybe having the dependencies (always the same) standardized can be a good choice.

If I understand correctly your idea @alkino , you would like every project to use a predefined set of git submodules (pybind11, cli11, fmt, spdlog, ...) and they would be automatically loaded in the CMake project and usable right away given a few lines of CMake code?

**Comment by alkino** [comment]
yes, because now, we are creating: https://github.com/BlueBrain/CoreNeuron/pull/179/files#diff-181622df1a9357af35c2fadd394ee56c everywhere

**Comment by matz-e** [comment]
> yes, because now, we are creating: https://github.com/BlueBrain/CoreNeuron/pull/179/files#diff-181622df1a9357af35c2fadd394ee56c everywhere

We could just revert to `CMake/Common` that the viz team uses ;)

@tristan0x the structure being optional is OK, IMO. For a lot of dependencies it makes sense.

**Comment by wizmer** [comment]
> We could just revert to CMake/Common that the viz team uses ;)
Please, no :)

I also agree for standardizing only the root location.

**Comment by mgeplf** [comment]
what goes in:
```
└── tests
    ├── integration
    └── non-regression
```
?

**Comment by ohm314** [comment]
The recommendations in `cpp/README.md` state:

> Note: if your project already has a cmake sub-directory, it is recommended to create the submodule in this directory instead of top-level.

I actually like that and have been setting it up like that wherever I introduce `(hpc|bbp)-coding-conventions`. Would this be lost? Please no :)

**Comment by matz-e** [comment]
> what goes in:
> 
> ```
> └── tests
>     ├── integration
>     └── non-regression
> ```
> 
> ?

![image](https://user-images.githubusercontent.com/2151261/74743157-3b182e80-5260-11ea-9d5b-cefd419111c0.png)

Can we use the more common `regression`?

**Comment by tristan0x** [comment]
> what goes in:
> 
> ```
> └── tests
>     ├── integration
>     └── non-regression
> ```
> 
> ?

These are just random names.
But a concrete use case would be the STEPS simulator: the documentation, examples, and integrations tests are located in 2 other git repositories. It would make sense for this project to use submodules like `3rdparty/tests/example/` and `3rdparty/tests/integration/` for instance.

**Comment by tristan0x** [comment]
> > what goes in:
> > ```
> > └── tests
> >     ├── integration
> >     └── non-regression
> > ```
> > 
> > 
> > ?
> 
> ![image](https://user-images.githubusercontent.com/2151261/74743157-3b182e80-5260-11ea-9d5b-cefd419111c0.png)
> 
> Can we use the more common `regression`?

whatever, do as you please

**Comment by tristan0x** [comment]
> > > what goes in:
> > > ```
> > > └── tests
> > >     ├── integration
> > >     └── non-regression
> > > ```
> > > 
> > > 
> > > ?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/2151261/74743157-3b182e80-5260-11ea-9d5b-cefd419111c0.png)
> > Can we use the more common `regression`?
> 
> whatever, do as you please

I couldn't care less even if you would decide to write an HTTP frontend with [WT](https://www.webtoolkit.eu/wt) for your C++ application and have a sub-module for pen-tests named `3rdparty/tests/penetration` :)

**Comment by mgeplf** [comment]
>  It would make sense for this project to use submodules like 3rdparty/tests/example/ and 3rdparty/tests/integration/ for instance.

Hmm, interesting use case.  I'm not sure I would have looked in 3rdparty for tests that were associated with the project, but that come from a different place (how I wish nlohmann/json did that - the submodule checkout is nuts.)

To be honest, though, I usually just look at the `.gitmodules` and go from there; if it's not clear, than I hope someone has created documentation.  Also, if anything, I would have expected `Catch2` to be in `tests`, and not in `src`, so it seems like it's hard to be prescriptive.

**Comment by tristan0x** [comment]
> (how I wish nlohmann/json did that - the submodule checkout is nuts.)

This is why I use the single-header distribution of nlohmann/json !

**Comment by mgeplf** [comment]
>  single-header distribution of nlohmann/json

And to think I got convinced by someone to remove catch2 from a repo, and use it as a submodule instead :)

Perhaps we should investigate https://cmake.org/cmake/help/latest/module/ExternalProject.html, and not use submodules at all - which means things can be conditionally checked out.

**Comment by jplanasc** [comment]
Looping in Viz team: @NadirRoGue  @chevtche :)

**Comment by matz-e** [comment]
> > single-header distribution of nlohmann/json
> 
> And to think I got convinced by someone to remove catch2 from a repo, and use it as a submodule instead :)

I'm not really a fan of single-header stuff in a code base.

> Perhaps we should investigate https://cmake.org/cmake/help/latest/module/ExternalProject.html, and not use submodules at all - which means things can be conditionally checked out.

That looks interesting. Could solve some issues w.r.t. how CMake has to be configured for the duality of the submodule vs external dependency use case when doing targets and properly compartmentalizing stuff.

**Comment by mgeplf** [comment]
> I'm not really a fan of single-header stuff in a code base.

I waver on this - submodules are nice in some cases, but since we're not in SVN land, we (often) end up cloning the full repo (b/c the `--depth` doesn't always have the commit we want, or the tags, or other random things I'm forgetting?).
So the size is just annoying:
- `nlohmann/json` is 439M, header only is 800K
- `Catch2` is 15M, 668K

> That looks interesting. Could solve some issues w.r.t. how CMake has to be configured for the duality of the submodule vs external dependency use case when doing targets and properly compartmentalizing stuff.

Agreed.  However, being that it's CMake, I fear that it will make things overly complicated, and not quite satisfy all the needs - plus debugging it will be So Much Fun (TM)

**Comment by alkino** [comment]
`ExternalProject` is really easy to use.

**Comment by mgeplf** [comment]
> ExternalProject is really easy to use.

Great! What's the best way to integrate it when deps can be provided partly from the system/spack, and partly from external?  I've never been happy w/ the `all or nothing` system we have in https://github.com/BlueBrain/libsonata/blob/master/CMakeLists.txt#L67, but at least the user has the choice of supplying the deps themselves.

Any chance you could make an example/PR to the above repo w/ how it would look with ExternalProject? (this is obviously not a high priority, so don't feel any obligation to - I'm just hoping that logic can be cleaned up - I'd be happy to get rid of the submodules, but still keep it easy to build standalone)

**Comment by pramodk** [comment]
> ExternalProject is really easy to use.

We have been using this in CoreNEURON project and we abandoned it. We choose it for simplicity of integration but annoying part is that it does CMake configure step for every project separately (meaning, imagine every project does its completely separate “cmake ..” step than parent project where it checks platform, compilers and so on). So  it’s like wrapper for building submodules as separate projects in their sandboxes.

I am also not entirely happy with submodules because of what Mike posted. For example, for NEURON project if someone does recursive clone then user end up >500MB of repo size (as submodules recursively clone many other things).

**Comment by matz-e** [comment]
> So the size is just annoying:
> 
>     * `nlohmann/json` is 439M, header only is 800K
> 
>     * `Catch2` is 15M, 668K

There's also `git clone --recursive --shallow-submodules` and the like. But they don't seem to be so reliable.

**Comment by jplanasc** [comment]
@tristan0x @matz-e @pramodk @mgeplf @alkino @ohm314 @wizmer :
Did we reach any conclusion on this?
Thanks!

**Comment by pramodk** [comment]
> There's also git clone --recursive --shallow-submodules and the like.

IIRC that works with git version >= 2.1 ? (BB5 git version is 1.8.3 and I thought we had new module?)

> Did we reach any conclusion on this?

I dont think so (?).

Just to add: current state of submodules in NEURON repo is :

```
○ → git clone --recursive git@github.com:neuronsimulator/nrn.git NN
Cloning into 'NN'...
remote: Enumerating objects: 77, done.
remote: Counting objects: 100% (77/77), done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 28105 (delta 26), reused 26 (delta 6), pack-reused 28028
Receiving objects: 100% (28105/28105), 89.21 MiB | 5.84 MiB/s, done.
Resolving deltas: 100% (19129/19129), done.
Checking out files: 100% (1817/1817), done.
Submodule 'docs/hoc' (https://github.com/neuronsimulator/progref-hoc.git) registered for path 'docs/hoc'
Submodule 'docs/python' (https://github.com/neuronsimulator/progref-py.git) registered for path 'docs/python'
Submodule 'docs/tutorials' (https://github.com/neuronsimulator/pythontutorial.git) registered for path 'docs/tutorials'
Submodule 'external/catch2' (https://github.com/catchorg/Catch2.git) registered for path 'external/catch2'
Submodule 'external/coding-conventions' (https://github.com/BlueBrain/hpc-coding-conventions.git) registered for path 'external/coding-conventions'
Submodule 'external/coreneuron' (https://github.com/BlueBrain/CoreNeuron.git) registered for path 'external/coreneuron'
Submodule 'modules/iv' (https://github.com/neuronsimulator/iv.git) registered for path 'external/iv'
Cloning into '/Users/kumbhar/Downloads/NN/docs/hoc'...
remote: Enumerating objects: 1238, done.
remote: Total 1238 (delta 0), reused 0 (delta 0), pack-reused 1238
Receiving objects: 100% (1238/1238), 506.72 KiB | 1.19 MiB/s, done.
Resolving deltas: 100% (769/769), done.
Cloning into '/Users/kumbhar/Downloads/NN/docs/python'...
remote: Enumerating objects: 178, done.
remote: Counting objects: 100% (178/178), done.
remote: Compressing objects: 100% (133/133), done.
remote: Total 1601 (delta 108), reused 78 (delta 45), pack-reused 1423
Receiving objects: 100% (1601/1601), 1.98 MiB | 2.84 MiB/s, done.
Resolving deltas: 100% (1040/1040), done.
Cloning into '/Users/kumbhar/Downloads/NN/docs/tutorials'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 223 (delta 1), reused 3 (delta 0), pack-reused 217
Receiving objects: 100% (223/223), 1.88 MiB | 2.67 MiB/s, done.
Resolving deltas: 100% (106/106), done.
Cloning into '/Users/kumbhar/Downloads/NN/external/catch2'...
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 25846 (delta 17), reused 26 (delta 8), pack-reused 25792
Receiving objects: 100% (25846/25846), 15.62 MiB | 4.76 MiB/s, done.
Resolving deltas: 100% (17982/17982), done.
Cloning into '/Users/kumbhar/Downloads/NN/external/coding-conventions'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 746 (delta 5), reused 1 (delta 0), pack-reused 731
Receiving objects: 100% (746/746), 177.88 KiB | 888.00 KiB/s, done.
Resolving deltas: 100% (488/488), done.
Cloning into '/Users/kumbhar/Downloads/NN/external/coreneuron'...
remote: Enumerating objects: 316, done.
remote: Counting objects: 100% (316/316), done.
remote: Compressing objects: 100% (176/176), done.
remote: Total 11560 (delta 197), reused 174 (delta 139), pack-reused 11244
Receiving objects: 100% (11560/11560), 35.37 MiB | 10.90 MiB/s, done.
Resolving deltas: 100% (8744/8744), done.
Cloning into '/Users/kumbhar/Downloads/NN/external/iv'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 1768 (delta 16), reused 14 (delta 11), pack-reused 1742
Receiving objects: 100% (1768/1768), 2.63 MiB | 2.56 MiB/s, done.
Resolving deltas: 100% (1306/1306), done.
Submodule path 'docs/hoc': checked out '5a917947bf443943630aa059a0f3e5173f1df855'
Submodule path 'docs/python': checked out '69e5062e4cae66103c864da5e801278198ea98d0'
Submodule path 'docs/tutorials': checked out '562eadc63b77e6b281a9d284e726479e929fb0e4'
Submodule path 'external/catch2': checked out '930f49a641aa6a495d264d7b5e7c007734da0b0c'
Submodule path 'external/coding-conventions': checked out '4c33e87ec9687c6c2f63bcd632b6868117f41c0b'
Submodule path 'external/coreneuron': checked out 'd9c7892a4fa321d02f0b8fb3a8ce3a5c112f7a72'
Submodule 'external/CLI11' (https://github.com/CLIUtils/CLI11.git) registered for path 'external/coreneuron/external/CLI11'
Submodule 'external/Random123' (https://github.com/BlueBrain/Random123.git) registered for path 'external/coreneuron/external/Random123'
Submodule 'external/mod2c' (https://github.com/BlueBrain/mod2c) registered for path 'external/coreneuron/external/mod2c'
Submodule 'external/nmodl' (https://github.com/BlueBrain/nmodl) registered for path 'external/coreneuron/external/nmodl'
Cloning into '/Users/kumbhar/Downloads/NN/external/coreneuron/external/CLI11'...
remote: Enumerating objects: 115, done.
remote: Counting objects: 100% (115/115), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 6765 (delta 43), reused 63 (delta 24), pack-reused 6650
Receiving objects: 100% (6765/6765), 3.73 MiB | 2.62 MiB/s, done.
Resolving deltas: 100% (4564/4564), done.
Cloning into '/Users/kumbhar/Downloads/NN/external/coreneuron/external/Random123'...
remote: Enumerating objects: 2012, done.
remote: Counting objects: 100% (2012/2012), done.
remote: Compressing objects: 100% (346/346), done.
remote: Total 2012 (delta 1653), reused 2011 (delta 1653), pack-reused 0
Receiving objects: 100% (2012/2012), 1.25 MiB | 1.62 MiB/s, done.
Resolving deltas: 100% (1653/1653), done.
Cloning into '/Users/kumbhar/Downloads/NN/external/coreneuron/external/mod2c'...
remote: Enumerating objects: 2352, done.
remote: Total 2352 (delta 0), reused 0 (delta 0), pack-reused 2352
Receiving objects: 100% (2352/2352), 1.02 MiB | 1.14 MiB/s, done.
Resolving deltas: 100% (1550/1550), done.
Cloning into '/Users/kumbhar/Downloads/NN/external/coreneuron/external/nmodl'...
remote: Enumerating objects: 7040, done.
remote: Total 7040 (delta 0), reused 0 (delta 0), pack-reused 7040
Receiving objects: 100% (7040/7040), 14.61 MiB | 4.02 MiB/s, done.
Resolving deltas: 100% (4870/4870), done.
Submodule path 'external/coreneuron/external/CLI11': checked out 'dd0d8e4fe729e5b1110232c7a5c9566dad884686'
Submodule 'extern/googletest' (https://github.com/google/googletest.git) registered for path 'external/coreneuron/external/CLI11/extern/googletest'
Cloning into '/Users/kumbhar/Downloads/NN/external/coreneuron/external/CLI11/extern/googletest'...
remote: Enumerating objects: 19843, done.
remote: Total 19843 (delta 0), reused 0 (delta 0), pack-reused 19843
Receiving objects: 100% (19843/19843), 7.23 MiB | 4.99 MiB/s, done.
Resolving deltas: 100% (14668/14668), done.
Submodule path 'external/coreneuron/external/CLI11/extern/googletest': checked out '2fe3bd994b3189899d93f1d5a881e725e046fdc2'
Submodule path 'external/coreneuron/external/Random123': checked out '5dfcec8313a47b2608728c76b07adbbf9ba39faf'
Submodule path 'external/coreneuron/external/mod2c': checked out 'ab00557515ae58ab71d3e41c57e909c7a9d36c0e'
Submodule path 'external/coreneuron/external/nmodl': checked out '7debe7095a0b5d082b7f42119e0be5075e576d1e'
Submodule 'cmake/hpc-coding-conventions' (https://github.com/BlueBrain/hpc-coding-conventions.git) registered for path 'external/coreneuron/external/nmodl/cmake/hpc-coding-conventions'
Submodule 'ext/cli11' (https://github.com/CLIUtils/CLI11.git) registered for path 'external/coreneuron/external/nmodl/ext/cli11'
Submodule 'ext/eigen' (https://github.com/eigenteam/eigen-git-mirror.git) registered for path 'external/coreneuron/external/nmodl/ext/eigen'
Submodule 'ext/fmt' (https://github.com/fmtlib/fmt.git) registered for path 'external/coreneuron/external/nmodl/ext/fmt'
Submodule 'ext/pybind11' (https://github.com/pybind/pybind11.git) registered for path 'external/coreneuron/external/nmodl/ext/pybind11'
Submodule 'ext/spdlog' (https://github.com/BlueBrain/spdlog.git) registered for path 'external/coreneuron/external/nmodl/ext/spdlog'
Cloning into '/Users/kumbhar/Downloads/NN/external/coreneuron/external/nmodl/cmake/hpc-coding-conventions'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 746 (delta 5), reused 1 (delta 0), pack-reused 731
Receiving objects: 100% (746/746), 177.88 KiB | 929.00 KiB/s, done.
Resolving deltas: 100% (488/488), done.
Cloning into '/Users/kumbhar/Downloads/NN/external/coreneuron/external/nmodl/ext/cli11'...
remote: Enumerating objects: 115, done.
remote: Counting objects: 100% (115/115), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 6765 (delta 43), reused 63 (delta 24), pack-reused 6650
Receiving objects: 100% (6765/6765), 3.73 MiB | 4.46 MiB/s, done.
Resolving deltas: 100% (4564/4564), done.
Cloning into '/Users/kumbhar/Downloads/NN/external/coreneuron/external/nmodl/ext/eigen'...
remote: Enumerating objects: 103968, done.
remote: Total 103968 (delta 0), reused 0 (delta 0), pack-reused 103968
Receiving objects: 100% (103968/103968), 98.96 MiB | 6.25 MiB/s, done.
Resolving deltas: 100% (84399/84399), done.
Cloning into '/Users/kumbhar/Downloads/NN/external/coreneuron/external/nmodl/ext/fmt'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 20181 (delta 4), reused 11 (delta 4), pack-reused 20164
Receiving objects: 100% (20181/20181), 9.78 MiB | 4.16 MiB/s, done.
Resolving deltas: 100% (13729/13729), done.
Cloning into '/Users/kumbhar/Downloads/NN/external/coreneuron/external/nmodl/ext/pybind11'...
remote: Enumerating objects: 11332, done.
remote: Total 11332 (delta 0), reused 0 (delta 0), pack-reused 11332
Receiving objects: 100% (11332/11332), 4.16 MiB | 3.63 MiB/s, done.
Resolving deltas: 100% (7649/7649), done.
Cloning into '/Users/kumbhar/Downloads/NN/external/coreneuron/external/nmodl/ext/spdlog'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 19651 (delta 0), reused 2 (delta 0), pack-reused 19644
Receiving objects: 100% (19651/19651), 39.01 MiB | 6.09 MiB/s, done.
Resolving deltas: 100% (13107/13107), done.
Submodule path 'external/coreneuron/external/nmodl/cmake/hpc-coding-conventions': checked out 'a1813c26dd75b8360b08893be5b2ecb485b816c4'
Submodule path 'external/coreneuron/external/nmodl/ext/cli11': checked out 'dd0d8e4fe729e5b1110232c7a5c9566dad884686'
Submodule 'extern/googletest' (https://github.com/google/googletest.git) registered for path 'external/coreneuron/external/nmodl/ext/cli11/extern/googletest'
Cloning into '/Users/kumbhar/Downloads/NN/external/coreneuron/external/nmodl/ext/cli11/extern/googletest'...
remote: Enumerating objects: 19843, done.
remote: Total 19843 (delta 0), reused 0 (delta 0), pack-reused 19843
Receiving objects: 100% (19843/19843), 7.23 MiB | 3.79 MiB/s, done.
Resolving deltas: 100% (14668/14668), done.
Submodule path 'external/coreneuron/external/nmodl/ext/cli11/extern/googletest': checked out '2fe3bd994b3189899d93f1d5a881e725e046fdc2'
Submodule path 'external/coreneuron/external/nmodl/ext/eigen': checked out 'b138753b1007d1eb0aeafddb558c1f4805c77003'
Submodule path 'external/coreneuron/external/nmodl/ext/fmt': checked out 'ee2b828b9a04ef6b9595e779a7878d4d27018cee'
Submodule path 'external/coreneuron/external/nmodl/ext/pybind11': checked out '9bb3313162c0b856125e481ceece9d8faa567716'
Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'external/coreneuron/external/nmodl/ext/pybind11/tools/clang'
Cloning into '/Users/kumbhar/Downloads/NN/external/coreneuron/external/nmodl/ext/pybind11/tools/clang'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 361 (delta 2), reused 2 (delta 0), pack-reused 353
Receiving objects: 100% (361/361), 147.50 KiB | 726.00 KiB/s, done.
Resolving deltas: 100% (151/151), done.
Submodule path 'external/coreneuron/external/nmodl/ext/pybind11/tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
Submodule path 'external/coreneuron/external/nmodl/ext/spdlog': checked out '7e81928f42824db990d855544e42f913cc2114c2'
Submodule path 'external/iv': checked out 'e7437032a8b2b21944ef4fcbe364f941852b7493'
```

Total `40` repos are downloaded and total size of clone is *513MB*.

If people have better suggestion to improve this situation, it will be very helpful!

**Comment by nrnhines** [comment]
No solution but to enter discussion, it seems that for most  external packages, the submodule build from a full repository download should be the last resort with first resort being pip, apt, yum, brew...
In between,  space and download time savings could result from tar.gz or shallow clone. A reasonably sophisticated search of the user machine could be useful for some situations, such as InterViews so that instead of downloading as a submodule, it is in fact available on the user machine via a proper -DIV_DIR. Given that many of these repositories change very rarely compared to NEURON/CoreNEURON, would it be possible to supply binaries that cmake would know where to find?

**Comment by mgeplf** [comment]
Like I said before, investigating https://cmake.org/cmake/help/latest/module/ExternalProject.html would make sense, because then at least one can check for dependencies (like what is needed for @nrnhines' comment), and conditionally get them - instead of blindly, recursively, downloading the all the submodules.

In `libsonata`, we have a `EXTLIB_FROM_SUBMODULES` [option](https://github.com/BlueBrain/libsonata/blob/master/CMakeLists.txt#L67), so one can build it without any submodules, but it's currently all or nothing.

**Comment by alkino** [comment]
Do we decide of a place for submodules?

**Comment by tristan0x** [comment]
> Do we decide of a place for submodules?

If I summarize the history of this ticket, the status is:
* _external code_ may reside in the top `3rdparty` directory.
* _External code_ designates any git submodule or embedded dependency like the single-header distribution of catch2 for instance.
* I agree with @ohm314 , if a project already has a top `cmake` directory, then it is recommended to put the submodule of the hbp-coding-conventions repository in there.
* no recommendation so far regarding the use of CMake external projects, git submodules, or embedded dependencies.

Unless someone disagrees about it and propose an alternative, I will add that in the guidelines at the end of this week.

**Comment by alkino** [comment]
Done in #79
